export const SET_CURRENT_USER = "SET_CURRENT_USER",
  GET_ERRORS = "GET_ERRORS",
  CLEAR_ERRORS = "CLEAR_ERRORS",
  FLASH_MSG = "FLASH_MSG",
  CLEAR_MSG = "CLEAR_MSG",
  VALID_RESET_TOKEN = "VALID_RESET_TOKEN",
  INVALID_RESET_TOKEN = "INVALID_RESET_TOKEN",
  INVALID_RESET_MSG = "INVALID_RESET_MSG";
